spring:
  application:
    name: liteflow-test

liteflow:
  rule-source-ext-data-map:
    serverAddr: 10.10.1.3:8848
    dataId: liteflow-test-flow.xml
    group: DEFAULT_GROUP
    namespace: e52f5e60-ed16-417b-92f2-77c3d473df40
#    username: nacos
#    password: nacos
